import React, { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Heart, Loader2, Search, ShoppingCart, SlidersHorizontal, X } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiClient } from '../../../api/client';

interface Category { id: number; name: string; slug: string }
interface Brand { id: number; name: string }
interface Product { id: number; name: string; description: string; basePrice: number; category: Category; brand: Brand; variants: { id: number; price: number }[] }
interface Page<T> { content: T[]; totalPages: number; number: number }
const money = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value);

export const ProductListPage: React.FC = () => {
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState(params.get('search') ?? '');
  const [categoryId, setCategoryId] = useState(params.get('categoryId') ?? '');
  const [brandId, setBrandId] = useState(params.get('brandId') ?? '');
  const [sort, setSort] = useState(params.get('sort') ?? 'id,desc');
  const [page, setPage] = useState(Number(params.get('page') ?? 0));
  const [filtersOpen, setFiltersOpen] = useState(false);
  const { data: categories = [] } = useQuery<Category[]>({ queryKey: ['categories'], queryFn: () => apiClient.get('/api/v1/categories').then(r => r.data) });
  const { data: brands = [] } = useQuery<Brand[]>({ queryKey: ['brands'], queryFn: () => apiClient.get('/api/v1/brands').then(r => r.data) });
  const { data, isLoading, isError } = useQuery<Page<Product>>({ queryKey: ['products', search, categoryId, brandId, sort, page], queryFn: () => apiClient.get('/api/v1/products', { params: { search: search || undefined, categoryId: categoryId || undefined, brandId: brandId || undefined, sort, page, size: 9 } }).then(r => r.data) });
  useEffect(() => { const next: Record<string, string> = {}; if (search) next.search = search; if (categoryId) next.categoryId = categoryId; if (brandId) next.brandId = brandId; if (sort !== 'id,desc') next.sort = sort; if (page) next.page = String(page); setParams(next, { replace: true }); }, [search, categoryId, brandId, sort, page, setParams]);
  const reset = () => { setSearch(''); setCategoryId(''); setBrandId(''); setSort('id,desc'); setPage(0); };
  const filterContent = <><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Bộ lọc</h2><button onClick={reset} className="text-xs text-[#0752b8]">Xóa tất cả</button></div><FilterBlock label="Danh mục">{categories.map(c => <Check key={c.id} text={c.name} checked={categoryId === String(c.id)} onChange={() => { setCategoryId(categoryId === String(c.id) ? '' : String(c.id)); setPage(0); }} />)}</FilterBlock><FilterBlock label="Thương hiệu">{brands.map(b => <Check key={b.id} text={b.name} checked={brandId === String(b.id)} onChange={() => { setBrandId(brandId === String(b.id) ? '' : String(b.id)); setPage(0); }} />)}</FilterBlock><FilterBlock label="Mức giá"><div className="grid grid-cols-2 gap-2"><input className="filter-input" placeholder="₫ Min"/><input className="filter-input" placeholder="₫ Max"/></div></FilterBlock><FilterBlock label="Bộ vi xử lý"><Check text="Intel Core"/><Check text="AMD Ryzen"/><Check text="Apple Silicon"/></FilterBlock><FilterBlock label="Tình trạng"><Check text="Còn hàng"/><Check text="Hàng mới về"/></FilterBlock></>;
  return <div className="mx-auto max-w-[1240px] px-4 py-9 sm:px-6"><div className="mb-2 text-[10px] text-[#7f8999]">Trang chủ　&gt;　Danh mục　&gt;　{categoryId ? categories.find(c => String(c.id) === categoryId)?.name : 'Sản phẩm'}</div><div className="mb-7 flex items-end justify-between gap-4"><div><h1 className="text-3xl font-extrabold tracking-tight">{categoryId ? categories.find(c => String(c.id) === categoryId)?.name : 'Sản phẩm công nghệ'}</h1><p className="mt-1 max-w-xl text-sm text-[#657084]">Khám phá dải sản phẩm công nghệ chính hãng với hiệu năng cao dành cho công việc và giải trí.</p></div><button onClick={() => setFiltersOpen(true)} className="flex items-center gap-2 rounded border px-3 py-2 text-sm lg:hidden"><SlidersHorizontal size={16}/> Bộ lọc</button></div><div className="grid gap-7 lg:grid-cols-[220px_1fr]"><aside className="hidden lg:block">{filterContent}</aside><section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><form onSubmit={e => { e.preventDefault(); setPage(0); }} className="flex h-9 max-w-sm flex-1 items-center rounded border border-[#dce2ec] bg-white px-3"><Search size={15} className="text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} className="ml-2 w-full text-xs outline-none" placeholder="Tìm sản phẩm..."/></form><label className="text-xs text-[#657084]">Sắp xếp theo: <select value={sort} onChange={e => { setSort(e.target.value); setPage(0); }} className="ml-2 rounded border border-[#dce2ec] bg-white px-3 py-2 text-xs outline-none"><option value="id,desc">Mới nhất</option><option value="name,asc">Tên A–Z</option><option value="basePrice,asc">Giá thấp đến cao</option><option value="basePrice,desc">Giá cao đến thấp</option></select></label></div>{isLoading ? <div className="flex h-72 items-center justify-center"><Loader2 className="animate-spin text-[#0752b8]"/></div> : isError ? <p className="rounded border bg-white p-8 text-center text-sm">Không thể tải sản phẩm. Vui lòng thử lại.</p> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data?.content.map(product => <ProductCard key={product.id} product={product}/>)}</div>{!data?.content.length && <p className="rounded border bg-white p-10 text-center text-sm text-slate-500">Không tìm thấy sản phẩm phù hợp.</p>}<Pagination page={page} total={data?.totalPages ?? 0} onChange={setPage}/></>}</section></div>{filtersOpen && <div className="fixed inset-0 z-[60] bg-slate-900/35 lg:hidden"><aside className="h-full w-[min(340px,90vw)] overflow-auto bg-white p-5"><button onClick={() => setFiltersOpen(false)} className="float-right"><X size={20}/></button>{filterContent}</aside></div>}</div>;
};
const FilterBlock = ({ label, children }: { label: string; children: React.ReactNode }) => <div className="border-b border-[#e8ebf2] py-4"><div className="mb-3 text-xs font-bold text-[#4e5a6e]">{label}</div><div className="space-y-2">{children}</div></div>;
const Check = ({ text, checked = false, onChange }: { text: string; checked?: boolean; onChange?: () => void }) => <label className="flex cursor-pointer items-center gap-2 text-xs text-[#5d687b]"><input type="checkbox" checked={checked} onChange={onChange ?? (() => undefined)} className="accent-[#0752b8]"/>{text}</label>;
const ProductCard = ({ product }: { product: Product }) => <article className="group relative overflow-hidden rounded border border-[#e2e7f0] bg-white p-3 transition hover:-translate-y-0.5 hover:shadow-md"><button className="absolute right-4 top-4 rounded bg-white/90 p-1.5 text-slate-400 hover:text-rose-500"><Heart size={16}/></button><Link to={`/products/${product.id}`}><div className="mb-3 flex h-36 items-center justify-center bg-gradient-to-br from-[#eff2f7] to-[#d9e0e9] text-center text-xs font-bold text-[#738094]">{product.brand?.name || 'TechPro'}<br/><span className="font-normal">Product image</span></div><p className="text-[10px] text-[#7b8798]">{product.category?.name}</p><h2 className="min-h-10 text-base font-bold leading-5 text-[#243148]">{product.name}</h2><p className="mt-1 line-clamp-1 text-[11px] text-[#7b8798]">{product.description || 'Sản phẩm công nghệ chính hãng'}</p><div className="mt-3 flex items-center justify-between"><strong className="text-base text-[#0752b8]">{money(product.variants?.[0]?.price ?? product.basePrice)}</strong><span className="rounded bg-[#e7f0ff] p-1.5 text-[#0752b8]"><ShoppingCart size={14}/></span></div></Link></article>;
const Pagination = ({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) => total > 1 ? <div className="mt-10 flex justify-center gap-2">{Array.from({ length: Math.min(total, 5) }, (_, i) => <button key={i} onClick={() => onChange(i)} className={`h-8 w-8 border text-xs ${i === page ? 'border-[#0752b8] bg-[#0752b8] text-white' : 'border-[#dce2ec] bg-white'}`}>{i + 1}</button>)}</div> : null;
